import { ComponentFixture, TestBed } from '@angular/core/testing';
import { ActivatedRoute, convertToParamMap, provideRouter } from '@angular/router';
import { BehaviorSubject } from 'rxjs';
import { DetailPageComponent } from './detail-page';

describe('DetailPageComponent', () => {
  let fixture: ComponentFixture<DetailPageComponent>;

  beforeEach(async () => {
    const routeParams = new BehaviorSubject(
      convertToParamMap({ detail: 'customer-data-platform' }),
    );

    await TestBed.configureTestingModule({
      imports: [DetailPageComponent],
      providers: [
        provideRouter([]),
        {
          provide: ActivatedRoute,
          useValue: { paramMap: routeParams.asObservable() },
        },
      ],
    }).compileComponents();

    fixture = TestBed.createComponent(DetailPageComponent);
    fixture.detectChanges();
  });

  afterEach(() => fixture.destroy());

  it('renders the descriptive page generated by a details JSON', () => {
    const text = fixture.nativeElement.textContent;
    const sections = fixture.nativeElement.querySelectorAll('.detail-section');

    expect(text).toContain('Dal dato grezzo a una visione affidabile del cliente');
    expect(text).toContain('Comprendere il contesto');
    expect(text).toContain('Rientra nell’orbita');
    expect(sections).toHaveLength(4);
    expect(fixture.nativeElement.querySelector('.detail-page__cosmos')).toBeTruthy();
  });

  it('renders a half-width image and expands it in a lightbox', () => {
    const imageButton = fixture.nativeElement.querySelector(
      'button[aria-label^="Ingrandisci immagine"]',
    ) as HTMLButtonElement;
    const image = imageButton.querySelector('img') as HTMLImageElement;

    expect(image.getAttribute('src')).toBe('/img/Rack%204.webp');
    expect(imageButton.closest('.detail-paragraph--with-image')).toBeTruthy();

    imageButton.click();
    fixture.detectChanges();
    expect(fixture.nativeElement.querySelector('.detail-lightbox')).toBeTruthy();

    const closeButton = fixture.nativeElement.querySelector(
      '.detail-lightbox__close',
    ) as HTMLButtonElement;
    closeButton.click();
    fixture.detectChanges();
    expect(fixture.nativeElement.querySelector('.detail-lightbox')).toBeFalsy();
  });
});
